# Generated by Django 4.0.4 on 2022-11-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
