# Generated by Django 4.0.4 on 2022-11-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_rename_code_statistiche_campo_dati'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistiche',
            options={'ordering': ['created']},
        ),
    ]
